import type { Metadata } from "next";
import { Inter } from "next/font/google"
import {ClerkProvider} from '@clerk/nextjs'
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";
import { SheetProvider } from "@/providers/sheet-provider";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] }) 

export const metadata: Metadata = {
  title: "Finance",
  description: "Generated by create next app",
  icons: "/whale.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={inter.className}>
        <QueryProvider>
          <SheetProvider />
          <Toaster />
        {children}
        </QueryProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
/* import type { Metadata } from "next";
import localFont from "next/font/local";
import {ClerkProvider} from '@clerk/nextjs'
import "./globals.css";
import { QueryProvider } from "@/providers/query-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <QueryProvider>
        {children}
        </QueryProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
 */